title: libraryofcons
markdown: kramdown
permalink: pretty

collections:
  scams:
    output: true
    permalink: /scams/:name/

  dictionary:
    output: true
    permalink: /dictionary/:name/

collections:
  resources:
    output: true
    permalink: /resources/:name/
